# Generated by Django 3.0.5 on 2021-04-30 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20210418_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='discussion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='posts_count',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='topics_count',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='date',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='last_author',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='last_date',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='replies',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='unread',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='views',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
